version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - app-data:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-d28r9cbuibrs73dsb33g-a.frankfurt-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=flight_booking
      - DB_USERNAME=filght_user  # Verify spelling
      - DB_PASSWORD=N4sd5ZzBho7yLiemZO2aqF0LjeKvQutf

volumes:
  app-data: